#!/bin/env python3

from sys import argv, exit
import importlib
import os

from mako.template import Template

TEMPLATE_DIR = './template'
MAIN_FILE = 'main.py'


def usage():
    print('Usage:')
    print(f'\t{argv[0]} [create] <number>')
    exit(1)


def check_num_args(number_of_args: int):
    if len(argv) - 1 != number_of_args:
        usage()


def create_task(task_num: str):
    print(f'Creating task {task_num}...')
    task_template = Template(filename=f'{TEMPLATE_DIR}/{MAIN_FILE}')
    os.makedirs(f'./{task_num}', exist_ok=True)
    with open(f'./{task_num}/{MAIN_FILE}', 'w') as fd:
        fd.write(task_template.render())


def run_task(task_num: str, subtask_num: str = ''):
    print(f'Executing task {task_num}{subtask_num}...')
    task = importlib.import_module(f'{task_num}.main')
    if subtask_num.lower() == 'a':
        task.run_a()
    elif subtask_num.lower() == 'b':
        task.run_b()
    else:
        task.run()


def main():
    if len(argv) < 2:
        usage()
    if 'create'.startswith(argv[1]):
        check_num_args(2)
        create_task(argv[2].zfill(2))
    elif argv[1].isnumeric():
        subtask_num = ''
        if len(argv) > 2:
            subtask_num = argv[2]
        run_task(argv[1].zfill(2), subtask_num)
    else:
        usage()


main()
